### ISSUE TITLE
自动刷图那进入地图直接返回主界面了，没刷

### ISSUE THREAD

**Issue by H-K-Y** [SimonShi1994/Princess-connection-farm#11]
很奇怪，买了体力直接进图，然后没刷直接出来了

**Comment by H-K-Y** [comment]
已经解决了，Automator.py的576和577行代码放到刷图后边就行了

**Comment by 1076472672** [comment]
编译器自动帮我弄的**错误的**格式。。。没注意到
感谢反馈，等下我再重写下刷图函数 XD

**Comment by HechengLi** [comment]
我也遇到了 把self.shuatuzuobiao放到while循环外面可以用了

**Comment by 1076472672** [comment]
询问得知是10图出现了这类问题，现已修复
