### ISSUE TITLE
juanzeng.py 脚本在BlueStack模拟器中无法使用

### ISSUE THREAD

**Issue by ytx1991** [SimonShi1994/Princess-connection-farm#112]
问题如题，我copy一个main.py改了改就可以用了，方便的话麻烦更新一下。

**Comment by 1076472672** [comment]
外置脚本打算全部整合到一起，master的外置脚本近期不会有恢复的打算
如果您拥有一定的代码理解能力，欢迎使用dev版本，能在群里反馈bug以便加快开发进程那就能好了）

**Comment by ytx1991** [comment]
是Q群吗，有群号吗

**Comment by 1076472672** [comment]
看README（逃
