### ISSUE TITLE
领活动每日奖励的时候点左上角没用

### ISSUE THREAD

**Issue by zipated** [SimonShi1994/Princess-connection-farm#119]
中间的礼物框已经出来了
然后就卡在这了

**Comment by zipated** [comment]
![image](https://user-images.githubusercontent.com/25282429/89633661-c18bff80-d8d6-11ea-8a1a-f692691c41ae.png)

**Comment by zipated** [comment]
需要手动点才能继续不然一直点左上角

**Comment by 1076472672** [comment]
这个窗口可以等30s让他自动消失，目前master与develop版本都已对这个进行处理 ）

**Comment by zipated** [comment]
好（
