### ISSUE TITLE
地下城进入有时候会卡住

### ISSUE THREAD

**Issue by FrostbiteXSW** [SimonShi1994/Princess-connection-farm#128]
具体表现就是卡在地下城选择难度的界面，重复点击界面最左侧，不能识别云海的山脉图片，必须先离开难度选择界面后（比如回到主页）再重新进入，脚本才能识别云海的山脉然后继续执行。根据脚本重复点击的位置，我估计是卡在了这个代码块：

    def dixiacheng(self, skip):

        ......

        # 撤退 如果 已经进入
        while True:
            screen = self.d.screenshot(format='opencv')
            if UIMatcher.img_where(screen, 'img/yunhai.bmp'):
                break
            if UIMatcher.img_where(screen, 'img/chetui.jpg', at=(738, 420, 872, 442)):
                self.lockimg('img/ok.bmp', elseclick=[(810, 433)], elsedelay=1, ifclick=[(592, 370)], ifbefore=0.5,
                             at=(495, 353, 687, 388))
                continue
            self.d.click(1, 100)    # 重复点击的位置
            time.sleep(0.3)

        ......

分支是master，因为dixiacheng_ocr这个方法有bug，我用的是不带ocr的方法。

**Comment by Dr-Bluemond** [comment]
yunhai.bmp中文字的部分有时会下移，导致识别不成功。更新换成不带文字的部分了
