### ISSUE TITLE
地下城伤害报告结算卡住

### ISSUE THREAD

**Issue by FrostbiteXSW** [SimonShi1994/Princess-connection-farm#131]
上次commit后又出现的新问题，目前就碰到两次，具体表现为卡在主菜单界面（回到标题画面的那个界面），重复点击（1，100）位置，脱离的方法是进入地下城再打一层（这个bug触发时地下城未能自动撤退），等到结算的时候就会恢复。估计是卡在了这个代码段：

def dixiacheng(self, skip):

    ......

    if skip is False:
        self.lockimg('img/shanghaibaogao.jpg', elseclick=[(1, 100)], ifclick=[(820, 492)], ifdelay=3)
        self.lock_no_img('img/shanghaibaogao.jpg', elseclick=[(820, 492)], elsedelay=3)

    ......

**Comment by Dr-Bluemond** [comment]
请问是从什么界面进入到主菜单界面的？

**Comment by FrostbiteXSW** [comment]
我后来研究了一下，这个问题应该不是脚本的问题，而是模拟器的问题。雷电模拟器4.0.30国际版，多开超过5个模拟器之后点击坐标偶尔会产生莫名的偏移，可能是计算机的负荷过高了，减少模拟器的数量后就没有再碰到这个问题了。
