### ISSUE TITLE
运行中USB device offline

### ISSUE THREAD

**Issue by FKWlalala** [SimonShi1994/Princess-connection-farm#15]
[W 200628 19:09:02 __init__:203] atx-agent has something wrong, auto recovering
Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\anaconda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:/Princess-connection-farm/main.py", line 16, in runmain
    a = Automator(address)
  File "D:\Princess-connection-farm\Automator.py", line 17, in __init__
    self.d = u2.connect(address)
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 1807, in connect
    return connect_usb(addr)
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 1848, in connect_usb
    return Device(serial)
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 241, in __init__
    wlan_ip = self.wlan_ip
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 404, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 208, in request
    self.__client._prepare_atx_agent()
  File "E:\anaconda\lib\site-packages\uiautomator2\__init__.py", line 285, in _prepare_atx_agent
    raise RuntimeError("USB device %s is offline" % self._serial)
RuntimeError: USB device 127.0.0.1:5555 is offline

在初始化和切换下一个农场号的时候有几率出现这个错误，然后那个农场号就会被跳过，我想请教一下这个是不是桥接设置出了问题，该怎么修正呢？谢谢

**Comment by 1076472672** [comment]
昨天在群里面也有人反馈了类似的bug，这个我们会看看怎么处理

**Comment by FKWlalala** [comment]
好的，有劳

**Comment by 1076472672** [comment]
127.0.0.1:5555？adb连接不正确？

**Comment by 1076472672** [comment]
adb connect 127.0.0.1:21503 测试下看逍遥模拟器的

**Comment by FKWlalala** [comment]
有点玄学，我刚才跑了五个捐碎片号，没有任何报错，同样的代码再跑剩下24个捐钱号就出错了。
adb的话好像我输任何地址都会给我修正成正确的127.0.0.1:5555
unable to connect to 127.0.0.1:5554:5554
[I 200629 00:48:42 init:155] uiautomator2 version: 2.9.6
[I 200629 00:48:42 init:352] Install minicap, minitouch
[D 200629 00:48:42 init:59] Use cached assets: C:\Users\Jiahao\.uiautomator2\cache\minitouch-7b41fbda87\minitouch
[D 200629 00:48:42 init:232] Push to /data/local/tmp/minitouch:0755
[I 200629 00:48:42 init:356] abi:x86 seems to be android emulator, skip install minicap
[D 200629 00:48:42 init:250] apk-debug package-info: {'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 6, 26, 9, 53, 59), 'last_update_time': datetime.datetime(2020, 6, 26, 9, 53, 59), 'signature': '337a63ff'}
[D 200629 00:48:42 init:251] apk-debug-test package-info: {'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 6, 26, 9, 54, 6), 'last_update_time': datetime.datetime(2020, 6, 26, 9, 54, 6), 'signature': '337a63ff'}
[I 200629 00:48:42 init:370] Already installed com.github.uiautomator apks
[D 200629 00:48:42 init:291] Real version: [0, 9, 4], Expect version: [0, 9, 4]
[D 200629 00:48:42 init:162] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d')
[I 200629 00:48:42 init:377] Check atx-agent version
[D 200629 00:48:42 init:390] Forward: local:tcp:6592 -> remote:tcp:7912
[D 200629 00:48:42 init:393] atx-agent version 0.9.4
Successfully init AdbDevice(serial=emulator-5554)
['emulator-5554', '127.0.0.1:5555']

**Comment by 1076472672** [comment]
应该有手机助手占用端口了，排查下看看

**Comment by 1076472672** [comment]
作者回复我说已经修复了，请等下一次pull更新

**Comment by SimonShi1994** [comment]
在之前的版本更新里已经加入对offline设备的筛选功能 :)
如果还会出现此类问题请反馈

**Comment by FKWlalala** [comment]
好的，谢谢
