### ISSUE TITLE
该适配一下新的地下城选择界面了（

### ISSUE THREAD

**Issue by zipated** [SimonShi1994/Princess-connection-farm#150]

**Comment by 1076472672** [comment]
dev已经适配了，master准备合并，目前没有打算~ ~

**Comment by zipated** [comment]
啊这，那没事了
（顺便感觉可以在python版本那注明个64位版本？

**Comment by FrostbiteXSW** [comment]
只是修改一下识别云海和点击的位置而已，不能先在master中更改吗？会战已经结束，大家也都回农场了，这个问题还是挺麻烦的
