### ISSUE TITLE
为什么不保留license？

### ISSUE THREAD

**Issue by yukinotech** [SimonShi1994/Princess-connection-farm#167]
本项目基于https://github.com/bbpp222006/Princess-connection开发。

虽然并不是fork别人的仓库，而是把别人的代码直接复制到这个仓库中。这种行为依然要遵循MIT license，保留原作者许可证。本项目不但删除了原作者许可证，还将许可证替换成了GPL3.0，我认为这种行为严重违反了开源精神。

希望本项目的负责人能够尊重原作者的劳动成果，保留原作者MIT license许可证

附录：
“MIT LicenseMIT是和BSD一样宽松的许可协议,作者只想保留版权,而无任何其他了限制.

也就是说,你必须在你的发行版里包含原许可协议的声明,无论你是以二进制发布的还是以源代码发布的。
* 你可以使用，复制和修改软件
* 你可以免费使用软件或出售
* 唯一的限制是，它是必须附有MIT授权协议

**Comment by Dr-Bluemond** [comment]
我查了一下，MIT协议不要求新增代码使用同样的协议。在「本项目基于https://github.com/bbpp222006/Princess-connection开发。」后面标注一下「MIT协议」这样的做法你看可以吗？

**Comment by 1076472672** [comment]
我搜寻了下，目前本项目仅有少部分代码逻辑（登陆，实名认证自动输入，图片寻找亮点）使用到了原作者的代码（_主要是写得太棒了_）
没有标注使用的原作者的代码使用MIT协议这一疏漏我感到非常抱歉，感谢提醒
目前dev已经更新标注，dev过一两天会合并进master
关于本项目与原作者的关系，原作者也在开发群，关系很好 =）

**Comment by yukinotech** [comment]
> 我搜寻了下，目前本项目仅有少部分代码逻辑（登陆，实名认证自动输入，图片寻找亮点）使用到了原作者的代码（_主要是写得太棒了_）
> 没有标注使用的原作者的代码使用MIT协议这一疏漏我感到非常抱歉，感谢提醒
> 目前dev已经更新标注，dev过一两天会合并进master
> 关于本项目与原作者的关系，原作者也在开发群，关系很好 =）

好的，我会持续关注，感谢及时反馈
