### ISSUE TITLE
在工会之家会点到宝石充值

### ISSUE THREAD

**Issue by pekoAAA** [SimonShi1994/Princess-connection-farm#19]

**Comment by 1076472672** [comment]
跳过剧情的逻辑没有优化好，不影响整体进程。
后面会优化下 )

**Comment by Yaoling2017** [comment]
同样遇到这个问题，因为工会之家界面也有caidan_yuan按钮所以可能会卡在跳剧情那。
在gonghuizhijia函数里最前面的
screen_shot_ = self.d.screenshot(format="opencv") 下面加一行：
screen_shot_ = screen_shot_[871:960, 463:549]，
这样只检测右上角是否有candan_yuan存在应该可以修正这个问题

**Comment by Dr-Bluemond** [comment]
应该解决了
