### ISSUE TITLE
不同模拟器的ADB端口

### ISSUE THREAD

**Issue by camenkc** [SimonShi1994/Princess-connection-farm#2]
夜神模拟器：adb connect 127.0.0.1:62001

逍遥安卓模拟器： adb connect 127.0.0.1:21503

天天模拟器：adb connect 127.0.0.1:6555 

海马玩模拟器 ：adb connect 127.0.0.1:53001

网易MUMU模拟器：adb connect 127.0.0.1:7555
转载：https://blog.csdn.net/qq_907465912/article/details/78913090

**Comment by SimonShi1994** [comment]
补充：
雷电模拟器：adb connect 127.0.0.1:5555
来自：https://www.cnblogs.com/Nick1994/p/8342046.html

**Comment by Dr-Bluemond** [comment]
我觉得只用adb start-server就可以连接上模拟器了，我用雷神模拟器试验了一下可以。如果其他模拟器也可以的话就不要特别指定端口了

**Comment by GENEVE0086** [comment]
补充：在MacOS下的MuMu模拟器
adb devices 看到有模拟器即可，输入命令adb shell能够进入命令行即为已连接，无需adb connect

**Comment by crifan** [comment]
此处Mac中网易Mumu模拟器，经研究发现是：
配置文件：
`/Users/YOUR_NAME/Library/Nemu/vms/myandrovm_vbox86/myandrovm_vbox86.nemu`
中是：
```xml
<Forwarding name="ADB_PORT" proto="1" hostip="127.0.0.1" hostport="5555" guestport="5555"/>
```
意思是：adb的port是：`5555`

所以此处用：

```bash
adb connect 127.0.0.1:5555
```

即可连接上网易Mumu
注：
* 第一次（等了好几秒后）会报错：`failed to connect to 127.0.0.1:5555`
* 再试一次即可提示：`already connected to 127.0.0.1:5555`

之后 `adb devices` 才能找到设备：

```bash
 adb devices
List of devices attached
127.0.0.1:5555    offline
emulator-5554    device
```

**Comment by TheAutumnOfRice** [comment]
目前已经有自动寻找的功能。
