### ISSUE TITLE
新号登录好像时先验证再出协议

### ISSUE THREAD

**Issue by klarkxy** [SimonShi1994/Princess-connection-farm#263]
截图没存
但很明显能看到卡在识别图片那里。
还是很阴间的识别几何体。
如果手点的快，还能继续下去
不然就只能等超时关闭重开了。

**Comment by TheAutumnOfRice** [comment]
你的脚本版本是什么？这个问题应该很早就被解决过了。
试着升级到最新的版本？（现在是v2.5）
如果还是不行可以进群交流。

**Comment by CyiceK** [comment]
我已经在 a31c6498e7b6db428105bef43868793f5fcf6466 把_login的return修改了，看更新后还会不会出现此类报错？
