### ISSUE TITLE
是否考虑将配置文件、日志分别单独放一个文件夹而非全都放在主目录下

### ISSUE THREAD

**Issue by klarkxy** [SimonShi1994/Princess-connection-farm#268]
![image](https://user-images.githubusercontent.com/6316992/109835675-65c40200-7c7e-11eb-8893-38f8144e72ed.png)
大概框了一下，虽然有gitignore，但感觉挺乱的。
蓝色方框是日志、输出相关的。
黄色方框是配置、自定义配置、任务相关的。

**Comment by TheAutumnOfRice** [comment]
会考虑。但考虑到更改存储结构带来的一系列麻烦，最近没有相关的更新计划。
