### ISSUE TITLE
快速截屏启动失败

### ISSUE THREAD

**Issue by yangcunbiao** [SimonShi1994/Princess-connection-farm#273]
![image](https://user-images.githubusercontent.com/45910752/111160072-b7e91980-85d4-11eb-9b1a-963892116638.png)

**Comment by TheAutumnOfRice** [comment]
很多情况会导致快速截图启动失败，比如雷电卡了。
可以在config中打开强制快速截图，此时检测到快速截图打开失败且设置了模拟器自启动时，会重启雷电进行尝试性修复。

**Comment by yangcunbiao** [comment]
好的，感谢

**Comment by yangcunbiao** [comment]
> 很多情况会导致快速截图启动失败，比如雷电卡了。
> 可以在config中打开强制快速截图，此时检测到快速截图打开失败且设置了模拟器自启动时，会重启雷电进行尝试性修复。
![image](https://user-images.githubusercontent.com/45910752/111393853-849dac00-86f4-11eb-951d-adfdec69a369.png)
打开强制快速截图后会一直重启
