### ISSUE TITLE
周年庆UI调整导致脚本失灵问题

### ISSUE THREAD

**Issue by TheAutumnOfRice** [SimonShi1994/Princess-connection-farm#295]
暂时无法确认全部波及范围，有相关信息会补充。

**Comment by UVJkiNTQ** [comment]
建议测试：

新增部分：
材质选择设定（中心设定框）
同名编队设定（确认框）

位置移动部分：
地下城boss位置
地下城撤退案件位置
游戏设定按钮（高帧率/跳过动画）
商店UI变动（上方Tab）
邮箱Tab部分

**Comment by CyiceK** [comment]
补充
- [ ] 图号
- [ ] 地下城撤退/次数
- [ ]  刷图跳过

**Comment by TheAutumnOfRice** [comment]
- [ ] 超级刷1-1
- [ ] d5地下城借人、撤退问题

**Comment by TheAutumnOfRice** [comment]
放弃了。
