### ISSUE TITLE
地下城无法撤退的问题

### ISSUE THREAD

**Issue by Clausy9** [SimonShi1994/Princess-connection-farm#3]
地下城在弹出结算奖励之前画面会明亮一段时间，这个时候也会识别到chetui.jpg，导致后续无法撤退。

**Comment by 1076472672** [comment]
是没有识别到取消，自己改下就好了。
我这虽然自己修复了，但是这个项目还是有很多问题需要改进

**Comment by SimonShi1994** [comment]
今天的更新应该已经修复这个问题，另外还修复了许多一些小bug
测试不够写的也不好 抛砖引玉了 : )

**Comment by 1076472672** [comment]
> 今天的更新应该已经修复这个问题，另外还修复了许多一些小bug
> 测试不够写的也不好 抛砖引玉了 : )

你这一更新，确实不错。
现在缺的是多开，一个一个账号处理有点慢。
我目前已经弄了一些功能
1.家园自动领取
2.行会点赞
3.优化处理速度
我还要测试下QAQ，一天 测+改

**Comment by Clausy9** [comment]
> 今天的更新应该已经修复这个问题，另外还修复了许多一些小bug
> 测试不够写的也不好 抛砖引玉了 : )

用下来发现有不少问题都是因为截图的判定，img里的图像很多截取的太小了 可以截大一点解决问题

**Comment by 1076472672** [comment]
> > 今天的更新应该已经修复这个问题，另外还修复了许多一些小bug
> > 测试不够写的也不好 抛砖引玉了 : )
> 
> 用下来发现有不少问题都是因为截图的判定，img里的图像很多截取的太小了 可以截大一点解决问题

因为opencv识别率问题，截图越小越精确，主要看怎么取舍

**Comment by 1076472672** [comment]
> > 今天的更新应该已经修复这个问题，另外还修复了许多一些小bug
> > 测试不够写的也不好 抛砖引玉了 : )
> 
> 用下来发现有不少问题都是因为截图的判定，img里的图像很多截取的太小了 可以截大一点解决问题

接下来的更新会判断按钮图片，不存在会进行手动点击
应该会修复这棘手的问题  ）
截图问题除非多次识别不出，一般没问题
