### ISSUE TITLE
安装 requirements 问题

### ISSUE THREAD

**Issue by FennyZSF** [SimonShi1994/Princess-connection-farm#319]
1. muggle ocr删库，请在requirements安装ocr2
2. 关于安装了requirements仍出现 no moduled
   请在requirements删除所有#行，删除所有中文，个人删除了muggle-ocr行
3.安装本地ocr2 https://github.com/myhub/tr需要安装git

例子
dbutils -i https://pypi.douban.com/simple
websocket_client==0.57.0 -i https://pypi.douban.com/simple
pandas -i https://pypi.douban.com/simple
openpyxl -i https://pypi.douban.com/simple
gevent==20.6.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
psutil==5.7.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
baidu-aip==2.2.18.0
matplotlib==3.1.3 -i https://pypi.tuna.tsinghua.edu.cn/simple/
opencv-python==4.3.0.36 -i https://pypi.tuna.tsinghua.edu.cn/simple/
uiautomator2 -i https://mirrors.aliyun.com/pypi/simple/
opencv-contrib-python==4.3.0.36 -i https://pypi.tuna.tsinghua.edu.cn/simple/
keyboard==0.13.5 -i https://pypi.tuna.tsinghua.edu.cn/simple/
retrying -i https://pypi.douban.com/simple

pypinyin
rich
cvxpy
cvxopt
brotli

flask==1.1.2 -i https://pypi.douban.com/simple
flask-marshmallow==0.13.0 -i https://pypi.douban.com/simple
flask-cors==3.0.8 -i https://pypi.douban.com/simple
flasgger==0.9.5 -i https://pypi.douban.com/simple

tensorflow == 2.4.0 -i https://pypi.douban.com/simple

numpy==1.19.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
pillow -i https://pypi.douban.com/simple
pyyaml -i https://pypi.douban.com/simple

**Comment by 17396743** [comment]
muggle ocr 这个库，用阿里云镜像还是可以下载到的。

**Comment by 17396743** [comment]
这个是我重新整理的requirements，2021年11月26日我试过了，可以直接装上，最多出现网络不好，要多下几次的情况。
https://github.com/17396743/pcr_farm_deploy
