### ISSUE TITLE
探索ocr出错

### ISSUE THREAD

**Issue by UVJkiNTQ** [SimonShi1994/Princess-connection-farm#323]
探索ocr在推完新图后报错，只打了一次。
探索3、4当时未3星。3是没打，4是未解锁。

ocr是否能判断未解锁，再补一次3？

**Comment by TheAutumnOfRice** [comment]
可能需要一些更详细的信息。
探索ocr有一个mode可以设置，有强制点第一个的也有从下网上点的。你可以看看那个mode参数。
