### ISSUE TITLE
下一步at偏移问题的检查与调整

### ISSUE THREAD

**Issue by TheAutumnOfRice** [SimonShi1994/Princess-connection-farm#328]
#325 
可能确实需要适当扩大at的范围。
具体是否存在偏移需要进一步观察实证。

**Comment by CyiceK** [comment]
https://github.com/SimonShi1994/Princess-connection-farm/commit/8c6e5662b485790f1da324899a58882ba99509c7 已经临时将战斗的xiayibu和xiayibu2的at撤除，据群友反馈尚可，目前先观察情况
