### ISSUE TITLE
地下城为什么进入云海后直接撤退了

### ISSUE THREAD

**Issue by wgli900222** [SimonShi1994/Princess-connection-farm#36]
农场号，嫖一下就行，需要做什么设置吗，谢谢。
P.S.用的mumu模拟器

**Comment by 1076472672** [comment]
当天手动非脚本进的地下城，检测到就会撤退退出
因为之前有地下城没有撤退的情况出现，所以会先执行一次撤退流程才进地下城

**Comment by AnakinShieh** [comment]
> 当天手动非脚本进的地下城，检测到就会撤退退出
> 因为之前有地下城没有撤退的情况出现，所以会先执行一次撤退流程才进地下城

这个问题挺严重的，部分新号总会弹出 可可罗那个地下城币 的教程然后就是一直卡死了，手动把可可罗那个教程点完了，后面就被这个脚本触发自动撤退了，结果因为这个浪费了好几天。

我看代码里似乎有处理可可罗教程的地方，但不知道为什么这里一直没触发过。

**Comment by wgli900222** [comment]
> > 当天手动非脚本进的地下城，检测到就会撤退退出
> > 因为之前有地下城没有撤退的情况出现，所以会先执行一次撤退流程才进地下城
> 
> 这个问题挺严重的，部分新号总会弹出 可可罗那个地下城币 的教程然后就是一直卡死了，手动把可可罗那个教程点完了，后面就被这个脚本触发自动撤退了，结果因为这个浪费了好几天。
> 
> 我看代码里似乎有处理可可罗教程的地方，但不知道为什么这里一直没触发过。

我是手动先把教程点完，然后注释那段撤退代码解决的。。。

**Comment by AnakinShieh** [comment]
> > > 当天手动非脚本进的地下城，检测到就会撤退退出
> > > 因为之前有地下城没有撤退的情况出现，所以会先执行一次撤退流程才进地下城
> > 
> > 
> > 这个问题挺严重的，部分新号总会弹出 可可罗那个地下城币 的教程然后就是一直卡死了，手动把可可罗那个教程点完了，后面就被这个脚本触发自动撤退了，结果因为这个浪费了好几天。
> > 我看代码里似乎有处理可可罗教程的地方，但不知道为什么这里一直没触发过。
> 
> 我是手动先把教程点完，然后注释那段撤退代码解决的。。。

我没搞明白游戏里那段教程的触发逻辑是啥，好像是账号在一个新的模拟器下登录就会触发？因为印象里手动点过不止一次，结果还是有这种情况。不知道有没有办法改游戏数据信息把这些教程全部跳过。

**Comment by 1076472672** [comment]
我在重写地下城 )
判断会更加好一点
