### ISSUE TITLE
兰德索尔杯（赛马）功能准备

### ISSUE THREAD

**Issue by GENEVE0086** [SimonShi1994/Princess-connection-farm#40]
官方今天发了官博，11号开始兰德索尔杯送钻活动，对广大玩家来说肯定是利好的，但是目前台日服都结束了赛马活动，不能进行提前调试，感觉开发者需要时间来准备这项功能，希望开发者能够尽快上线功能。

同时也希望各位点进来看的各位用户不要着急，做好一段时间内需要自己给农场号手动过赛马的准备，开发者辛苦了

**Comment by 1076472672** [comment]
功能已实现 )
