### ISSUE TITLE
goumaimana.py报错

### ISSUE THREAD

**Issue by HDQC** [SimonShi1994/Princess-connection-farm#46]
![QQ截图20200712023542](https://user-images.githubusercontent.com/48578555/87231298-a8cc1f00-c3e8-11ea-9f8a-44404822bb95.png)
其他的脚本正常 但这个会出错 请求您的帮助！

**Comment by HDQC** [comment]
对了 出现这种报错的时候 会一直点击右上角 而且还会显示登陆下一组账号，然而并没有登就是了。

**Comment by 1076472672** [comment]
goumaimana(1) # 购买10次mana
这里没有填值，所以报错

**Comment by HDQC** [comment]
谢谢大佬！在今天更新后 我在goumaimana.py里面的a.goumaimana() 里面加了数字就可以用了。不过好像goumaimana.py里面goumaimana()的括号一直是空的，没有预设值。
