### ISSUE TITLE
IndexError: list index out of range错误

### ISSUE THREAD

**Issue by archer0079** [SimonShi1994/Princess-connection-farm#51]
[I 200713 21:45:38 init:155] uiautomator2 version: 2.10.0
[I 200713 21:45:38 init:352] Install minicap, minitouch
[D 200713 21:45:38 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minitouch-7b41fbda87\minitouch
[D 200713 21:45:38 init:232] Push to /data/local/tmp/minitouch:0755
[I 200713 21:45:38 init:355] abi:x86 seems to be android emulator, skip install minicap
[D 200713 21:45:38 init:250] apk-debug package-info: {'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 7, 13, 21, 27, 24), 'last_update_time': datetime.datetime(2020, 7, 13, 21, 27, 24), 'signature': '1e5c9a8b'}
[D 200713 21:45:38 init:251] apk-debug-test package-info: {'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 7, 13, 21, 27, 25), 'last_update_time': datetime.datetime(2020, 7, 13, 21, 27, 25), 'signature': '1f9d8214'}
[I 200713 21:45:38 init:370] Already installed com.github.uiautomator apks
[D 200713 21:45:38 init:290] Real version: [0, 9, 4], Expect version: [0, 9, 4]
[D 200713 21:45:38 init:162] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d')
[I 200713 21:45:38 init:377] Check atx-agent version
[D 200713 21:45:38 init:390] Forward: local:tcp:9715 -> remote:tcp:7912
[D 200713 21:45:38 init:393] atx-agent version 0.9.4
Successfully init AdbDevice(serial=emulator-5554)
Traceback (most recent call last):
  File "c:/adb/Princess-connection-farm-master/main.py", line 211, in <module>
    lines, emulatornum = connect()
  File "c:/adb/Princess-connection-farm-master/main.py", line 150, in connect
    while lines[0] != 'List of devices attached ':
IndexError: list index out of range

**Comment by Dr-Bluemond** [comment]
检查运行位置是否为项目根目录

**Comment by GENEVE0086** [comment]
请自己先用命令行使用adb devices查看表头，保证与150行处单引号内字符串完全一致，List of devices attached这部分很有可能会因为一个空格的不匹配导致脚本将所有的返回字符串删除，就会爆出这种错误

**Comment by TheAutumnOfRice** [comment]
新版已经修复
