### ISSUE TITLE
能否用 anaconda3 中的 python 3.9 来运行该项目？

### ISSUE THREAD

**Issue by Never2333** [SimonShi1994/Princess-connection-farm#521]
致开发团队：

由于本人学校要求使用 anaconda 3 来进行一系列的 python 作业，所以请教一下能否用其自带的 python 3.9 来运行该项目。

不敢再在本机上安装第二 python，怕环境变量配置紊乱，导致课业项目无法进行。

还请多多指教。

**Comment by UVJkiNTQ** [comment]
可以是可以，但建议建venv，因为依赖的版本问题。

**Comment by TheAutumnOfRice** [comment]
请自行研究anaconda建虚拟环境的方法。
