### ISSUE TITLE
显示图片检测完毕就停了，要怎么用啊？

### ISSUE THREAD

**Issue by 202012900350** [SimonShi1994/Princess-connection-farm#529]
显示图片检测完毕就停了，要怎么用啊？
![NJI{3H7$C72P(0MZ SG8AES](https://user-images.githubusercontent.com/101036658/225681855-45d69369-af8c-4cba-aea4-44ea01caf1da.png)

**Comment by TheAutumnOfRice** [comment]
这里是在联网检测更新。可以尝试检查，更改VPN设置。

**Comment by 202012900350** [comment]
也没开vpn啊

**Comment by 202012900350** [comment]
要先开脚本再开模拟器是吧

**Comment by CyiceK** [comment]
> 总之是网络原因，检查网络设置，是否能连接到github。 或者自己把更新检查代码注释掉。 @CyiceK 这里也可以考虑加一个timeout

35ac5d37d3c7e93bc9391a4bff2ac90386abe36f 已经加上了5s的timeout，共重试两次
