### ISSUE TITLE
群加不进去，自己弄了好久

### ISSUE THREAD

**Issue by Aescn** [SimonShi1994/Princess-connection-farm#530]
这个报错怎么弄啊
![image](https://user-images.githubusercontent.com/85007494/228276594-810ed03b-7ae3-4942-8636-c151283fa715.png)

**Comment by Aescn** [comment]
另外不能开一个二群或者tg、dc之类的渠道吗？

**Comment by TheAutumnOfRice** [comment]
你这个是python的依赖安装的问题，和这个项目无关。
二群的话，群主失踪了，我们也懒得搞。
