### ISSUE TITLE
图片错误

### ISSUE THREAD

**Issue by felixxyq** [SimonShi1994/Princess-connection-farm#6]
昨天的更新里img目录下maoxian.jpg图片实际上是地下城的图片

**Comment by felixxyq** [comment]
自行替换后功能正常了

**Comment by 1076472672** [comment]
maoxian.jpg 确实是地下城图片，昨天更新是修复庆典开始无法识别
maoxian这个文件名有歧义，我下次pull顺便改了 XD

**Comment by SimonShi1994** [comment]
其实maoxian.jpg一开始就是地下城的图片，这个名字是为了说明这是冒险界面的标志，确实起的不好XD
img的文件名里还有不少起的不规范的（）

**Comment by 1076472672** [comment]
6/20 已修复
